ai_service:
  active_service: huggingface

  huggingface:
    models:
      summary_model: "microsoft/phi-2"
      category_model: "facebook/bart-large-mnli"
      severity_model: "facebook/bart-large-mnli"
      recommendation_model: "microsoft/phi-2"

    labels:
      categories:
        - "Flight Ops"
        - "Avionics"
        - "Weather"
        - "Human Factors"
        - "Mechanical"
      severities:
        - "low"
        - "medium"
        - "high"
        - "critical"

    prompts:
      # Available variables: {raw_text}
      summarization: >-
        <|user|>
        Summarize the following flight event in one concise sentence.
        Event: "{raw_text}"
        <|endofuser|>
        <|assistant|>
        Summary:

      # Available variables: {raw_text}, {category}, {severity}
      recommendation: >-
        <|user|>
        Analyze the flight report and provide one concise recommendation.
        Event: "{raw_text}"
        Category: {category}
        Severity: {severity}
        <|endofuser|>
        <|assistant|>
        Recommendation:
