ai_service:
  # Available services: huggingface, mock
  active_service: mock

  huggingface:
    models:
      summary_model: "microsoft/phi-2"
      category_model: "facebook/bart-large-mnli"
      severity_model: "facebook/bart-large-mnli"
      recommendation_model: "microsoft/phi-2"

    prompts:
      # Available variables: {raw_event_text}
      summarization: >-
        <|user|>
        Summarize the following flight event in one concise sentence.
        Event: "{raw_event_text}"
        <|endofuser|>
        <|assistant|>
        Summary:

      # Available variables: {raw_event_text}, {category}, {severity}
      recommendation: >-
        <|user|>
        Analyze the flight report and provide one concise recommendation.
        Event: "{raw_event_text}"
        Category: {category}
        Severity: {severity}
        <|endofuser|>
        <|assistant|>
        Recommendation:

  labels:
    categories:
      - "Flight Ops"
      - "Avionics"
      - "Weather"
      - "Human Factors"
      - "Mechanical"
    severities:
      - "low"
      - "medium"
      - "high"
      - "critical"

database:
  # Available handlers: sqlite
  active_handler: sqlite

  sqlite:
    db_file: "flight_reports.db"